title: Mahdi Safarzadeh
logo: /assets/img/profile.jfif
theme: jekyll-theme-minimal

# Social links
github: https://github.com/loopersosa
email: safarzadehmahdi33@gmail.com
linkedin: https://www.linkedin.com/in/mahdi-safarzadeh-99b727211/
telegram: https://t.me/magatowski
